-- SQL Script to set up the Users table in Supabase
-- Run this in the Supabase SQL Editor

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'user'::text CHECK (role IN ('admin', 'user'))
);

-- NOTE: Passwords must be hashed using Bcrypt before insertion.
-- The dashboard now includes a built-in Register tab to handle this.

CREATE TABLE IF NOT EXISTS public.potholes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    latitude FLOAT8 NOT NULL,
    longitude FLOAT8 NOT NULL,
    image_url TEXT,
    severity TEXT DEFAULT 'low'::text CHECK (severity IN ('high', 'medium', 'low')),
    pothole BOOLEAN DEFAULT true,
    type TEXT DEFAULT 'pothole'::text,
    confidence FLOAT8 DEFAULT 0.0,
    status TEXT DEFAULT 'pending'::text,
    report_count INT DEFAULT 1,
    last_reported_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.user_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    latitude FLOAT8 NOT NULL,
    longitude FLOAT8 NOT NULL,
    media_url TEXT NOT NULL,
    type TEXT NOT NULL, -- 'image' or 'video'
    description TEXT,
    status TEXT DEFAULT 'pending'::text CHECK (status IN ('pending', 'reviewed', 'approved', 'rejected')),
    user_id BIGINT REFERENCES public.users(id)
);

-- RPC for incrementing report count safely
CREATE OR REPLACE FUNCTION increment_report_count(row_id bigint)
RETURNS int
LANGUAGE plpgsql
AS $$
DECLARE
  new_count int;
BEGIN
  UPDATE potholes
  SET report_count = report_count + 1
  WHERE id = row_id
  RETURNING report_count INTO new_count;
  
  RETURN new_count;
END;
$$;

